// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Git) DeepCopyInto(out *Git) {
	*out = *in
	if in.AccountSecret != nil {
		in, out := &in.AccountSecret, &out.AccountSecret
		*out = new(v1.ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Git.
func (in *Git) DeepCopy() *Git {
	if in == nil {
		return nil
	}
	out := new(Git)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitTemplate) DeepCopyInto(out *GitTemplate) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitTemplate.
func (in *GitTemplate) DeepCopy() *GitTemplate {
	if in == nil {
		return nil
	}
	out := new(GitTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceDetails) DeepCopyInto(out *NamespaceDetails) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceDetails.
func (in *NamespaceDetails) DeepCopy() *NamespaceDetails {
	if in == nil {
		return nil
	}
	out := new(NamespaceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitialize) DeepCopyInto(out *ProjectInitialize) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitialize.
func (in *ProjectInitialize) DeepCopy() *ProjectInitialize {
	if in == nil {
		return nil
	}
	out := new(ProjectInitialize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectInitialize) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitializeList) DeepCopyInto(out *ProjectInitializeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectInitialize, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitializeList.
func (in *ProjectInitializeList) DeepCopy() *ProjectInitializeList {
	if in == nil {
		return nil
	}
	out := new(ProjectInitializeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectInitializeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitializeQuota) DeepCopyInto(out *ProjectInitializeQuota) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitializeQuota.
func (in *ProjectInitializeQuota) DeepCopy() *ProjectInitializeQuota {
	if in == nil {
		return nil
	}
	out := new(ProjectInitializeQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectInitializeQuota) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitializeQuotaList) DeepCopyInto(out *ProjectInitializeQuotaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectInitializeQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitializeQuotaList.
func (in *ProjectInitializeQuotaList) DeepCopy() *ProjectInitializeQuotaList {
	if in == nil {
		return nil
	}
	out := new(ProjectInitializeQuotaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectInitializeQuotaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitializeQuotaSpec) DeepCopyInto(out *ProjectInitializeQuotaSpec) {
	*out = *in
	in.ResourceQuotaSpec.DeepCopyInto(&out.ResourceQuotaSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitializeQuotaSpec.
func (in *ProjectInitializeQuotaSpec) DeepCopy() *ProjectInitializeQuotaSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectInitializeQuotaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitializeQuotaStatus) DeepCopyInto(out *ProjectInitializeQuotaStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitializeQuotaStatus.
func (in *ProjectInitializeQuotaStatus) DeepCopy() *ProjectInitializeQuotaStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectInitializeQuotaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitializeSpec) DeepCopyInto(out *ProjectInitializeSpec) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(Git)
		(*in).DeepCopyInto(*out)
	}
	if in.GitTemplate != nil {
		in, out := &in.GitTemplate, &out.GitTemplate
		*out = new(GitTemplate)
		**out = **in
	}
	if in.NamespaceDetails != nil {
		in, out := &in.NamespaceDetails, &out.NamespaceDetails
		*out = new(NamespaceDetails)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitializeSpec.
func (in *ProjectInitializeSpec) DeepCopy() *ProjectInitializeSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectInitializeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectInitializeStatus) DeepCopyInto(out *ProjectInitializeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectInitializeStatus.
func (in *ProjectInitializeStatus) DeepCopy() *ProjectInitializeStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectInitializeStatus)
	in.DeepCopyInto(out)
	return out
}
