apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projectinitializes.redhatcop.redhat.io
spec:
  group: redhatcop.redhat.io
  names:
    kind: ProjectInitialize
    listKind: ProjectInitializeList
    plural: projectinitializes
    singular: projectinitialize
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ProjectInitialize is the Schema for the projectinitializes API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ProjectInitializeSpec defines the desired state of ProjectInitialize
          properties:
            cluster:
              type: string
            desc:
              type: string
            displayName:
              type: string
            env:
              type: string
            git:
              description: Git
              properties:
                desc:
                  description: Description of the repository to create/clone
                  type: string
                owner:
                  description: Account to copy template
                  type: string
                private:
                  description: Private or public repository
                  type: boolean
                provider:
                  description: The host provider type
                  enum:
                  - GitHub
                  - GitLab
                  - BitBucket
                  type: string
              required:
              - desc
              - owner
              - private
              - provider
              type: object
            gitTemplate:
              description: Git
              properties:
                accountSecret:
                  description: The token of the account that the template will copy
                    to
                  properties:
                    apiVersion:
                      description: API version of the referent.
                      type: string
                    fieldPath:
                      description: 'If referring to a piece of an object instead of
                        an entire object, this string should contain a valid JSON/Go
                        field access statement, such as desiredState.manifest.containers[2].
                        For example, if the object reference is to a container within
                        a pod, this would take on a value like: "spec.containers{name}"
                        (where "name" refers to the name of the container that triggered
                        the event) or if no container name is specified "spec.containers[2]"
                        (container with index 2 in this pod). This syntax is chosen
                        only to have some well-defined way of referencing a part of
                        an object. TODO: this design is not final and this field is
                        subject to change in the future.'
                      type: string
                    kind:
                      description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                      type: string
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                      type: string
                    namespace:
                      description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                      type: string
                    resourceVersion:
                      description: 'Specific resourceVersion to which this reference
                        is made, if any. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency'
                      type: string
                    uid:
                      description: 'UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids'
                      type: string
                  type: object
                owner:
                  description: Account of the template to copy
                  type: string
                repo:
                  description: Repo to copy
                  type: string
              required:
              - accountSecret
              - owner
              - repo
              type: object
            quotaSize:
              type: string
            team:
              type: string
          required:
          - desc
          - displayName
          - env
          - team
          type: object
        status:
          description: ProjectInitializeStatus defines the observed state of ProjectInitialize
          properties:
            namespaceCreated:
              type: boolean
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
